### PR TITLE
Overhaul process reaping and terminal control

### LINKED ISSUE #3805: When called from another shell script, fish can't read
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.3.1

**OS/terminal used**: Debian Linux (jessie), xterm

I wrote a script using `#!/usr/bin/fish`.  The script calls `read`.  Works fine from command line but not when called from another script.

## Reproduction steps

````
nr@homedog ~/net> call-fish-read 
fish: Couldn't grab control of terminal
tcsetpgrp: Interrupted system call

nr@homedog ~/net> fish-read
say something⏎                                                                  asdf

asdf
nr@homedog ~/net> /usr/bin/fish --version
fish, version 2.3.1-dirty
````

Scripts are attached in a zip file, but it may be easier to view source here.

Here is `fish-read`:

````
#!/usr/bin/fish

read -p 'echo -n say something >&2 ' -l -s answer
echo $answer
````

and here is `call-fish-read`:

````
#!/bin/ksh

mumble=$(fish-read)
echo $mumble
````

N.B. I downloaded a nightly of fish 2.4.0 from SUSE, and behavior is even more frustrating---the shell just hangs trying to read file descriptor 3.  Not sure what's up with that (I poked at it with `strace -f`.)

Would love to have a workaround that enables me to use a fish script as a tool in other scripts.
[demo-scripts.zip](https://github.com/fish-shell/fish-shell/files/749392/demo-scripts.zip) 

May be related to #3223 and #1258.

### LINKED ISSUE #3952: Job handling is broken.
I have an issue running the command `sudo echo lol | grep lol`. This command is not as trivial as it seems because grep is a fish function, calling `command grep --color=auto $argv` behind the scene.

Now, a simple run of that command gives
```
layus@klatch ~/p/fish> sudo echo lol | grep lol
# Nothing happens, job is blocked. Entering ^Z.
Job 1, 'sudo echo lol | grep lol' has stopped
layus@klatch ~/p/fish> jobs
Job	Group	CPU	State	Command
1	7318	0%	stopped	sudo echo lol | grep lol
2	7319	0%	stopped	command grep --color=auto $argv
layus@klatch ~/p/fish> fg
Send job 1, 'sudo echo lol | grep lol' to foreground
[sudo] password for layus : 
layus@klatch ~/p/fish> fg
Send job 2, 'command grep --color=auto $argv' to foreground
lol
layus@klatch ~/p/fish> 
```

This behavior is not changed by #3922, and may relate to #206. We see that fish starts two jobs for one user job, and that these jobs are managed separately. Digging in the source code, we can find that one job is created for the top-level pipeline.

[exec_job](https://github.com/fish-shell/fish-shell/blob/c0de8afaf34471478db83b38f9994e6d937e6517/src/exec.cpp#L368-L1130) starts processes for each step of the pipeline. When it reaches `grep`, it detects a fish function and calls [internal_exec_helper](https://github.com/fish-shell/fish-shell/blob/c0de8afaf34471478db83b38f9994e6d937e6517/src/exec.cpp#L667-L668) to start its body.
That function parses the function body and starts a new job to to handle its content.
That new job is not aware of its parent context, and start with a new pgid. Fish gives that process control over the terminal, removing it from `sudo`.

When `sudo` starts, it receives a SIGTTOU and gets stopped. Fish blocks because the grep job is still running, and unrelated to the sudo job.

Running ps to compare fish to other shells gives

<pre>
 PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
===== ===== ===== ===== ======== ===== ===== ==== ====== =========
    1   764   764   764 ?           -1 Ss       0   0:00 sshd [...]
  764 31954 31954 31954 ?           -1 Ss       0   0:00  \_ sshd: me [priv]
31954 31956 31954 31954 ?           -1 S     1000   0:00  |   \_ sshd: me@pts/0
31956 31957 31957 31957 pts/0     7319 Ss    1000   0:00  |       \_ -zsh
31957  7306  7306 31957 pts/0     7319 S     1000   0:00  |           \_ ./fish -d4
 7306  7317  7306 31957 pts/0     7319 S     1000   0:00  |               \_ ./fish -d4
 7306  7318  <b>7318</b> 31957 pts/0     <b>7319 T</b>        0   0:00  |               \_ sudo echo lol
 7306  7319  <b>7319</b> 31957 pts/0     <b>7319</b> S+    1000   0:00  |               \_ grep --color=auto lol
  764  7390  7390  7390 ?           -1 Ss       0   0:00  \_ sshd: me [priv]
 7390  7392  7390  7390 ?           -1 S     1000   0:00  |   \_ sshd: me@pts/4
 7392  7393  7393  7393 pts/4     7470 Ss    1000   0:00  |       \_ -zsh
 7393  7460  7460  7393 pts/4     7470 S     1000   0:00  |           \_ zsh
 7460  7470  <b>7470</b>  7393 pts/4     <b>7470</b> S+       0   0:00  |               \_ sudo echo lol
 7460  7471  <b>7470</b>  7393 pts/4     <b>7470</b> S+    1000   0:00  |               \_ grep --color=auto lol
  764  7474  7474  7474 ?           -1 Ss       0   0:00  \_ sshd: me [priv]
 7474  7476  7474  7474 ?           -1 S     1000   0:00      \_ sshd: me@pts/5
 7476  7477  7477  7477 pts/5     7530 Ss    1000   0:00          \_ -zsh
 7477  7519  7519  7477 pts/5     7530 S     1000   0:00              \_ bash
 7519  7530  <b>7530</b>  7477 pts/5      <b>7530</b> S+       0   0:00                  \_ sudo echo lol
 7519  7531  <b>7530</b>  7477 pts/5      <b>7530</b> S+    1000   0:00                  \_ grep lol
</pre>

We can see that the current TPGID is 7319 while the sudo command has a PGID of 7318. It's status is T, which means that the process is "stopped, either by a job control signal or because it is being traced". Here it is because of the aforementioned SIGTTOU.
We see that other shells give the same PGID to all the subcommands.

The extra fish process is the "keepalive fork" used by fish. I still wonder why fish needs it while other shells do not, but it is not important.

From a job control point of view, fish shows two running jobs in `jobs` output, while bash and zsh will show only one, even if zsh seems to distinguish between the processes of the job. (^Z was added for clarity, but does not appear in the terminal)

<pre>
ZSH:
--(layus@klatch)--> grep () { command grep --color=auto "$@"; }   
--(layus@klatch)-->  sudo echo lol | grep lol                      
[sudo] password for layus: <em>^Z</em>
zsh: running    sudo echo lol | grep --color=auto lol
--(layus@klatch)--> jobs
[1]  + suspended           sudo echo lol | 
       suspended (signal)  grep --color=auto lol

BASH:
layus@klatch:~$ grep () { command grep --color=auto "$@"; }
layus@klatch:~$ sudo echo lol | grep lol
[sudo] password for layus: <em>^Z</em>

[1]+  Stopped                 sudo echo lol | grep lol
layus@klatch:~$ jobs
[1]+  Stopped                 sudo echo lol | grep lol
</pre>

We need to make function invocation part of the same job as their context. I believe that one command line should create one job in the jobs view. That would also immediately fix the SIGTTOU issue for sudo because both processes will have the same PGID and will both have control over the terminal.
Because they are handled exctly like function, begin/end blocks would be fixed at the same time.

---

On current master (version 2.5.0-259-gc0de8afa-dirty, aka c0de8afa).

### LINKED ISSUE #4178: Variant of the `No TTY for interactive shell`
I've been experiencing a persistent variant of the `No TTY for interactive shell` error trying to install oh-my-fish on fish v2.6.0:
```
≻ curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    426      0 --:--:-- --:--:-- --:--:--   427
100 16622  100 16622    0     0  25023      0 --:--:-- --:--:-- --:--:-- 25023
Existing installation detected at /Users/patrick.bohan/.local/share/omf
Would you like to remove the existing installation? (y/N): <W> fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
```

Requested ticket information:
```
≻ fish --version
fish, version 2.6.0
≻ echo $version
2.6.0
≻ uname -a
Darwin patrickbohanwerallyin.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
≻ echo $TERM
xterm-256color
```

**It does indeed when I run without customizations**, i.e. `sh -c 'env HOME=$(mktemp -d) fish'`. 
I'm rather new to fish -- I've mostly stuck to customizing my `fish_prompt` -- but I'm at a loss for what change might have done this. I'm happy to narrow this down on my own but I'm not entirely sure the best way to do that. (I tried `fish --debug-level=3` but I'm not sure exactly what I might be looking for.)

I tried the [alternate install](https://github.com/oh-my-fish/oh-my-fish#installation) and the first `read` succeeded but a second one failed. I got a stack trace that might (hopefully) is useful:
```
[patrick.bohan|~]0≻ curl -L https://get.oh-my.fish > install
                    fish install --path=~/.local/share/omf --config=~/.config/omf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    384      0 --:--:-- --:--:-- --:--:--   385
100 16622  100 16622    0     0  24041      0 --:--:-- --:--:-- --:--:-- 24041
Existing installation detected at /Users/patrick.bohan/.local/share/omf
Would you like to remove the existing installation? (y/N): ⏎                                                                                                                                                                                                                  read> y
This will uninstall Oh My Fish and all plugins and themes from
/Users/patrick.bohan/.local/share/omf.
Are you sure you want to continue? (y/N): <E> fish: src/reader.cpp:1559: failed assertion: input_initialized
<E> fish: Backtrace:
<E> fish: 0   reader_push(wchar_t const*) + 1056
<E> fish: 1   builtin_read(parser_t&, io_streams_t&, wchar_t**) + 1482
<E> fish: 2   builtin_run(parser_t&, wchar_t const* const*, io_streams_t&) + 334
<E> fish: 3   exec_job(parser_t&, job_t*) + 3736
<E> fish: 4   parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 5   parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 6   parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 7   parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 8   parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 9   parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t) + 134
<E> fish: 10  internal_exec_helper(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned int, block_type_t, io_chain_t const&) + 1017
<E> fish: 11  exec_job(parser_t&, job_t*) + 2885
<E> fish: 12  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 13  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 14  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 15  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 16  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 17  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t) + 134
<E> fish: 18  internal_exec_helper(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned int, block_type_t, io_chain_t const&) + 1017
<E> fish: 19  exec_job(parser_t&, job_t*) + 2885
<E> fish: 20  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 21  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 22  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 23  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 24  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 25  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t) + 134
<E> fish: 26  internal_exec_helper(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned int, block_type_t, io_chain_t const&) + 1017
<E> fish: 27  exec_job(parser_t&, job_t*) + 2885
<E> fish: 28  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 29  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 30  parse_execution_context_t::run_if_statement(parse_node_t const&) + 461
<E> fish: 31  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 529
<E> fish: 32  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 33  parse_execution_context_t::run_if_statement(parse_node_t const&) + 461
<E> fish: 34  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 529
<E> fish: 35  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 36  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 37  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 38  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 39  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t) + 134
<E> fish: 40  internal_exec_helper(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned int, block_type_t, io_chain_t const&) + 1017
<E> fish: 41  exec_job(parser_t&, job_t*) + 2885
<E> fish: 42  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 43  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 44  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 45  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 46  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 47  reader_read(int, io_chain_t const&) + 1877
<E> fish: 48  main + 3118
<E> fish: 49  start + 1
<E> fish: 50  53  ???                                 0x0000000000000004 0x0 + 4
fish: 'fish install --path=~/.local/sh…' terminated by signal SIGABRT (Abort)
[patrick.bohan|~]134≻
```

Unfortunately I haven't found any work around for this problem. I've looked at several seemingly related tickets ( #3805 , #3345 , #2980, #1844 ) but none appeared to be helpful for my situation.

Any help would be greatly appreciated.

### LINKED ISSUE #4238: [ctrl-C] fails to terminate job when `read` is involved
fish version: 2.6.0
uname: Linux xxx 4.11.7-041107-generic #201706240231 SMP Sat Jun 24 06:33:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
TERM: screen-256color (tmux)

The problem occurs with a plain shell too.

I use a `inotifywait`-while-end call for cyclic compiling (no differences between the used build system here `cargo` but same problem with `make`):

    inotifywait -mrq -e close_write Cargo.toml src/ libgerrit/ --format "%w/%f" | while read CHANGEDFILE
        clear
        cargo check; and cargo build
        echo "DONE"
    end

I cannot stop the program via `STRG+C`.

### LINKED ISSUE #4929: Piping interactive bash to a function stops the process
I initially reported this issue [here](https://github.com/fish-shell/fish-shell/issues/1362#issuecomment-382531245).

## Description

When I pipe `bash -i` into a function (in this case, `grep`), the process gets stopped. @faho did some investigating and said:

> The problem with bash -i seems to be that it grabs the terminal for itself - strace -e ioctl shows it doing one with TIOCSPGRP - which is the underlying syscall for tcsetpgrp on linux.
-- https://github.com/fish-shell/fish-shell/issues/1362#issuecomment-382709142

## My environment

```sh
$  fish --version
fish, version 2.7.1

$ echo $version
2.7.1

$ uname -a
Darwin Joshs-MacBook-Air-2.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color
```

## Demo / how to reproduce

```sh
# ===== Setup =====

# get a clean environment
$ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell

# shorten the prompt
josh@Joshs-MacBook-Air-2 /U/josh> function fish_prompt; echo '> '; end


# ===== Demo the issue =====

# hangs (I'll press C-c)
> bash -i -c 'echo hello >&2' | grep whatever
Job 1, 'bash -i -c 'echo hello >&2' | g…' has stopped

# its state is "stopped"
> jobs
Job	Group	State	Command
1	24863	stopped	bash -i -c 'echo hello >&2' | grep whatever

# when I foreground it, it completes as expected
> fg
Send job 1, 'bash -i -c 'echo hello >&2' | grep whatever' to foreground
hello


# ===== Slight variations that don't exhibit the issue =====

# use the grep command instead of the function
> bash -i -c 'echo hello >&2' | command grep whatever
hello

# run bash without the -i flag
> bash -c 'echo hello >&2' | grep whatever
hello


# ===== Other potentially useful info =====

# the grep function
> type grep
grep is a function with definition
function grep
    command grep --color=auto $argv
end
```

### LINKED ISSUE #5210: eval in config.fish inside a second instance stops the shell
Running 2.7.1-1449-gdeb6d477

If you have the following in your `config.fish`:

```fish
if status is-interactive
   eval (touch /dev/null)
end
```

Then when starting a new instance of fish inside an existing instance, the behaviour is as follows:

```
> echo $SHLVL
1
> fish
Job 1, 'fish' has stopped
> echo $SHLVL
1
> jobs
Job	Group	State	Command
1	26930	stopped	fish
> fg
Send job 1, 'fish' to foreground
zanchey@oxygen ~> echo $SHLVL
2
zanchey@oxygen ~> exit
> echo $SHLVL
1
```

This bites me because I have `eval (python3 -m virtualfish)` in my `config.fish`.

### PR DESCRIPTION
**Pull request by mqudsi**
I _believe_ this finally safely does away with the keepalive process. I think the problem is that we were waiting on all child processes in `process_mark_finished_children` which caused premature reaping of terminated processes before their process group could be joined by new processes in the same job.

Additionally, there was a deadlock in `try_select` that didn't show up until that change was made.

This should fix #4178 (which manifests in two *entirely* different ways depending on whether connected over SSH and FreeBSD vs Linux) and quite likely some other issues as well.

~~This branch should likely be squash-merged.~~

---

Partially addresses #206.

Closes #3805. Closes #3952. Closes #4178. Closes #4238. Closes #4929. Closes #5210.

### CODE REVIEW

**Comment by mqudsi** [comment]
Also fixes #3952 :)

**Comment by mqudsi** [comment]
Also fixes #3805

**Comment by mqudsi** [comment]
Also fixes #5210

**Comment by mqudsi** [comment]
@ridiculousfish @krader1961 any thoughts?

I've installed this branch as my main driver on my FreeBSD, WSL, and now macOS as it appears to include some highly platform-specific behavior. Would appreciate if others could try it out for a few days, you never know where edge cases can pop up.

**Comment by faho** [comment]
>Instead of reaping all child processes when we receive a SIGCHLD, try
reaping only processes belonging to process groups from
fully-constructed jobs.

This basic idea seems entirely logical to me, and I struggle to think how that would make it any worse. Are there cases where that now doesn't reap a process at all? Is it a problem to leave unreaped jobs around for a bit?

I don't think so, but this stuff is full of weird edges and spooky corners.

------------------

I've done some cursory testing, and I can confirm that #5210 seems to be solved. I can't confirm #3952, and that should still  be an issue.

The case there is:

```fish
sudo echo lol | grep lol
```

with `grep` being a function. The big problem is that that is two separate jobs, because fish forgets the current job as soon as it executes the function. Which is something separate from the keepalive stuff, but not made worse by it either.

**Comment by faho** [comment]
I can confirm #3805 as fixed, pgroup-wise.

**Comment by mqudsi** [comment]
There is no problem in keeping the zombie processes unreaped until the job is constructed, but the problem is whether or not the reaping function is executed at the right places, because when a process is reaped it changes the internal state of the job, and `select_try` would hang when it is waiting for IO that never comes becomes and it deadlocks waiting for the job to change state (which never happens).

----

That's weird, I tested #3952 it yesterday (it even came up in the autosuggest from history) but you're right, it is indeed not fixed.

```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> function grep
                                        command grep --color=auto
                                    end
mqudsi@ZBook /m/c/U/m/r/fish-shell> sudo echo lol | grep lol
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
mqudsi@ZBook /m/c/U/m/r/fish-shell> sudo echo lol | grep lol
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

**Comment by faho** [comment]
>That's weird, I tested #3952 it yesterday (it even came up in the autosuggest from history) but you're right, it is indeed not fixed.

There is a timing component to it, so it's possible you just got unlucky and got a false-positive.

**Comment by mqudsi** [comment]
I also changed the debug levels of some tracing output so that `-d3` can be used for sanely debugging job status and progression.

**Comment by faho** [comment]
>I also changed the debug levels of some tracing output so that -d3 can be used for sanely debugging job status and progression.

Ooh yes. Last I looked, the most spammy part was input - "checking X against mapping Y" or something - but I think I already increased the level on that.

I still believe something like #4818 or a file-based thing (`fish --debug=input,reader` to get messages from input.cpp and reader.cpp) would be better, but we're a bit too chatty in low levels in general.

**Comment by mqudsi** [comment]
😄 Yeah, it was the key binding mapping that would print page after page of output.

File: src/input.cpp [hunk 1]
```diff
@@ -384,7 +384,7 @@ static bool input_mapping_is_match(const input_mapping_t &m) {
     const wcstring &str = m.seq;
 
     assert(str.size() > 0 && "zero-length input string passed to input_mapping_is_match!");
-    debug(4, L"trying to match mapping %ls", escape_string(m.seq.c_str(), ESCAPE_ALL).c_str());
+    debug(8, L"trying to match mapping %ls", escape_string(m.seq.c_str(), ESCAPE_ALL).c_str());
```
Comment (faho) [inline src/input.cpp]: Honestly: Just remove this one. There's not been a bug here for quite a while, and we wouldn't use this debug to catch it.

File: src/reader.cpp [hunk 2]
```diff
@@ -1743,8 +1743,17 @@ static void reader_interactive_init() {
         // Eventually we just give up and assume we're orphaend.
         for (unsigned long loop_count = 0;; loop_count++) {
             pid_t owner = tcgetpgrp(STDIN_FILENO);
-            shell_pgid = getpgrp();
+            // 0 is a valid return code from `tcsetpgrp()` under FreeBSD, and testing
```
[the remark this answers is not in the document]
Comment (faho) [reply src/reader.cpp]: in which case... why doesn't mine return 0?

It says it "will return the foreground process group ID of that terminal if there is one, and some value larger than 1 that is not presently a process group ID otherwise". Which just strikes me as quite stupid, and just asking for TOCTTOUs. Why not just 0?

File: src/proc.cpp [hunk 3]
```diff
@@ -264,6 +264,12 @@ int job_signal(job_t *j, int signal) {
     return res;
 }
 
+static void mark_job_complete(const job_t *j) {
+    for (auto &p : j->processes) {
+        p->completed = 1;
```
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/proc.cpp]: Yeah, c boolean that I should probably just change over to a real `bool`.

File: src/proc.cpp [hunk 4]
```diff
@@ -789,7 +823,7 @@ bool terminal_give_to_job(const job_t *j, bool cont) {
     // http://curiousthing.org/sigttin-sigttou-deep-dive-linux In all cases, our goal here was just
     // to hand over control of the terminal to this process group, which is a no-op if it's already
     // been done.
-    if (tcgetpgrp(STDIN_FILENO) == j->pgid) {
+    if (j->pgid == -2 || tcgetpgrp(STDIN_FILENO) == j->pgid) {
         debug(4, L"Process group %d already has control of terminal\n", j->pgid);
```
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/proc.cpp]: I'm not sure that's true. If a job was all functions or builtins that didn't fork, pgid should be `-2`, but since it's actually operating under the scope of the current shell instance, it technically has control of the shell, no?

File: src/reader.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/reader.cpp]: Yup. Thanks.

File: src/proc.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (faho) [reply src/proc.cpp]: Shouldn't the pgid then be the pgid of the shell?

AFAIK, "-2" here is the sentinel value for "hasn't been set up yet".

File: src/postfork.cpp [hunk 5]
```diff
@@ -137,7 +137,7 @@ bool maybe_assign_terminal(const job_t *j) {
     assert(j->pgid > 1 && "maybe_assign_terminal() called on job with invalid pgid!");
 
     if (j->get_flag(JOB_TERMINAL) && j->get_flag(JOB_FOREGROUND)) {  //!OCLINT(early exit)
-        if (tcgetpgrp(STDIN_FILENO) == j->pgid) {
+        if (j->pgid == -2 || tcgetpgrp(STDIN_FILENO) == j->pgid) {
```
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/postfork.cpp]: You're right, I didn't catch that assert (was working on results of a find operation).

File: src/parse_execution.cpp [hunk 6]
```diff
@@ -1223,6 +1223,7 @@ parse_execution_result_t parse_execution_context_t::run_1_job(tnode_t<g::job> jo
         // Check to see if this contained any external commands.
         bool job_contained_external_command = false;
         for (const auto &proc : job->processes) {
+            /* debug(1, L"Parsed job with head %ls", proc->argv0()); */
```
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/parse_execution.cpp]: I'll keep it but bump it up to level 4. It's the clearest way of seeing what job was parsed first in a pipeline.

[the remark this answers is not in the document]
Comment (faho) [reply src/parse_execution.cpp]: Okay!

File: src/proc.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/proc.cpp]: I'm pretty sure the code that sets the pgid isn't called since iirc it's basically set on the first forked command in the chain. If there was no pgid-related code, -2 is indeed a reflection on the fact that at no point was a pgid assigned.

I'd have to double-check, though.

File: src/reader.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/reader.cpp]: 0 is actually a valid pid for the top-level process (`init` under Linux, `kernel` under FreeBSD).

Under Linux in my test cases I was getting -1, but when SSH'd to FreeBSD I was getting zero. The FreeBSD man page has this to say:

```
     The tcgetpgrp() function returns the value of the process group ID of the foreground process group
     associated with the terminal device.  If there is no foreground process group, tcgetpgrp() returns an
     invalid process ID.
```

A process gets assigned a parent id of zero when its own parent dies (giving parentship of the process to init, whose job is to then call `waitpid` to kill the zombie process). I'm not sure if that's what was happening in my test case (or how that could be what was happening in my case, and I'm suspecting that FreeBSD is returning zero to imply invalid.

I should clarify that comment.

File: src/reader.cpp [hunk 7]
```diff
@@ -3318,7 +3329,9 @@ const wchar_t *reader_readline(int nchars) {
     }
 
     if (!reader_exit_forced()) {
-        if (tcsetattr(0, TCSANOW, &old_modes) == -1) {
+        // The order of the two conditions below is important. Try to restore the mode
+        // in all cases, but only complain if not interactive.
```
Comment (mqudsi) [inline src/reader.cpp]: That should be "if interactive"

File: src/reader.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (faho) [reply src/reader.cpp]: >0 is actually a valid pid for the top-level process (init under Linux, kernel under FreeBSD).

Init is always PID 1 in linux and [FreeBSD](https://www.freebsd.org/doc/handbook/basics-processes.html). PID 0 on linux is the swapper and scheduler, but those don't have children or terminals, so we shouldn't ever have to care about them. I'm not sure if they actually "do processy stuff" on BSD.

>A process gets assigned a parent id of zero when its own parent dies

On linux it gets 1, as above. And I'm pretty sure that applies to BSD too, since I'm pretty sure that also reparents to init.

[the remark this answers is not in the document]
Comment (mqudsi) [reply src/reader.cpp]: Sorry, I had the pid for init wrong. FreeBSD does reparent to 1 as well. Which makes this even more bizarre, and lends credence to the theory that 0 does indeed represent invalid under FreeBSD.. yet indicates that a subsequent attempt at `tcsetpgrp` will succeed.

File: src/postfork.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/postfork.cpp]: I imagine while 1 is a valid pgid that there's no (useful?) way for a command executed under fish to end up with that pgid?

[the remark this answers is not in the document]
Comment (faho) [reply src/postfork.cpp]: I think the only way is "init=/bin/fish" on the kernel commandline. Which might be useful.

**Comment by ridiculousfish** [comment]
I'd be totally thrilled to eliminate the keepalive process. I hope this works!!

I think I understand the theory of this PR. Before we would create a keep-alive process, and kill it once the job is constructed. With this PR, we no longer construct a keep-alive. Rather we allow the pgroup to become a zombie, and just delay reaping it by never calling waitpid(), only waiting on certain processes. That's pretty clever. I understand old WSL did not support this (zombies were not a WSL thing), but this was recently improved to make zombie processes real, so this might really work.

The tricky part is that waitpid() is not like select(): you can wait for THIS PARTICULAR child, or wait for ANY child, but not wait for a *set* of children. If you disallow waiting for ANY child, you might wind up waiting on a long-lived background process and thereby hang. So how do we ensure we aren't waiting for a background process?

I think the reason this works is as follows: parser_t puts new jobs at the beginning of the job list, and there can only be one constructed foreground job. We only call wait() after adding a foreground job, so we never end up waiting on a background job. So that's working by accident  the job list happens to put new jobs at the beginning. Yet I think this has hit onto something really great.

I'd like to see the following:

1. `process_mark_finished_children` currently takes one parameter, `wants_await`. Let's change it to `block_on_foreground`. If that's set, this happens:
  a. It asserts that there's at most one job that's foreground AND constructed.
  b. If there is such a job, wait on that job with WNOHANG = 0 (i.e. allow it to block).
  c. For every background job, wait with WNOHANG set.

2. This PR currently has 9 commits, some of which seem to be fixes for previous commits. Can you please clean this up into reviewable chunks? For example I see commented-out code like `// needs_keepalive = true`, we shouldn't have that sort of thing (we shouldn't have `needs_keepalive` at all if this works!) `git rebase -i`  is a good tool for this sort of cleanup.

3. There's multiple uses of `-2` to mean a not-yet constructed job, I think it's time to introduce a constant for this!

4. `proc_wait_any()` invoked from `builtin_wait` is going to be a problem. In particular if you call builtin `wait` from within a function and the function is in a pipeline, you may end up reaping the keepalive process. (We'll want to add a test case for this.)

File: src/proc.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/proc.cpp]: builtins that do not fork keep pgrp -2.

**Comment by mqudsi** [comment]
I ended up spending pretty much the entire day on this. I didn't expect it to be that hard after the work that was already done, but I ran into some corner cases with `waitpid` (documented in the comments.. extensively) that made me pull out half my hair. I've based and rebased more times than I can count, but I think I have the branch in a state where it can (after review) be merged without squashing. Each commit should individually pass the tests.

The most important (non-aesthetic) changes are in 525f329 and  f987183. The changes in 6add7d are small, but do have significant ramifications to error handling in the `job_continue` code.

@ridiculousfish apologies in advance for 4eb01c6, but please see the commit log. Others needing this treatment include the unnamed return result containing the `STATUS_*` values (so that one can distinguish between functions returning an actual int, e.g. 'int count_active_blah_blah_blah` vs those return a status (e.g. `exec_subshell`) and those returning a boolean masquerading as an int (some of which have been replaced with the new `Tristate` which is very similar to `maybe_t<bool>`). 

I introduced RAII wrappers in places to clean up error handling, though there was one place where I was forced to use a lambda as the cleanup depends on which parts of the function were successfully executed.

Debug level 3 generally means "be verbose about job execution" while level 4 means "include details about waits and io handling". 

Most dead code was trimmed from `exec.cpp` and (particularly) `proc.cpp`. The overall flow in `proc.cpp` should be significantly easier to follow, and code has been grouped together in a more-C++ less-C fashion there. In general, self-documenting code styles have been used where possible. Lots more refactoring is needed for the codebase as a whole to take advantage of some of these idioms, but it's not relevant to this branch and shouldn't be committed here.

I tried to keep both code and functional testing in mind when breaking up the changes into commits. I hope I have made things fairly easy to follow and provided sufficient commentary for anyone trying to puzzle something out, now or in the future.

Feedback is most welcome.

Now excuse me while I go forget all the useless things I learned today.

**Comment by mqudsi** [comment]
@ridiculousfish I replied there,  it shouldn't be a problem. Do you have any thoughts on the actual logic changes in this PR?

**Comment by mqudsi** [comment]
@ridiculousfish https://github.com/mqudsi/fish-shell/blob/keep_zombies/src/enum_set.h

File: src/proc.h [hunk 8]
```diff
@@ -192,6 +192,8 @@ class job_t {
     /// Sets the command.
     void set_command(const wcstring &cmd) { command_str = cmd; }
 
+    const wcstring preview() const { return processes.empty() ? L"" : processes[0]->argv0() + wcstring(L" ..."); }
```
Comment (ridiculousfish) [inline src/proc.h]: First `const` is unnecessary. Should be `wcstring preview() const { ...} 

Can you add a comment here describing what this is for?

File: src/common.h [hunk 9]
```diff
@@ -31,6 +31,16 @@
 #include "maybe.h"
 #include "signal.h"  // IWYU pragma: keep
 
+// some versions of ncurses globally define TRUE/FALSE
```
Comment (ridiculousfish) [inline src/common.h]: We shouldn't need to be doing this; please remove these defines and TRUE/FALSE definitions.

File: src/common.h [hunk 10]
```diff
@@ -978,6 +988,32 @@ enum {
     STATUS_INVALID_ARGS = 121,
 };
 
+/// Replaces usages of int-as-bool to incorporate minus-one-on-failure behavior with a strictly-typed
```
Comment (ridiculousfish) [inline src/common.h]: This seems like an unnecessary abstraction to me. I don't think we should introduce this Tristate type. It's not motivated by this commit.

File: src/proc.h [hunk 11]
```diff
@@ -139,23 +140,23 @@ typedef std::unique_ptr<process_t> process_ptr_t;
 typedef std::vector<process_ptr_t> process_list_t;
 
 /// Constants for the flag variable in the job struct.
-enum job_flag_t {
+enum class JobFlag {
```
Comment (ridiculousfish) [inline src/proc.h]: fish style is snake_case not CamelCase; this should be `job_flag_t`.

File: src/enum_set.h [hunk 12]
```diff
@@ -0,0 +1,46 @@
+#pragma once
+
+#include <bitset>
+
+template<typename T>
+class EnumSet {
```
Comment (ridiculousfish) [inline src/enum_set.h]: Ok I like this idea! I think we may even want to add bitwise operator overloads later.

File: src/enum_set.h [hunk 13]
```diff
@@ -0,0 +1,46 @@
...
+private:
+	std::bitset<8 * sizeof(typename std::underlying_type<T>::type)> bitmask {0};
+	int index_of(T t) const;
```
Comment (ridiculousfish) [inline src/enum_set.h]: `index_of` should be `static`. BTW you'll probably find it a lot more pleasant to define all these methods inline:

    static int index_of(T t) {
        static_cast<typename std::underlying_type<T>::type>(t);
    }

No more duplicated templates, etc.

File: src/exec.cpp [hunk 14]
```diff
@@ -985,22 +985,17 @@ static bool exec_process_in_job(parser_t &parser, process_t *p, job_t *j,
 }
 
 void exec_job(parser_t &parser, job_t *j) {
+    assert(j != nullptr);
```
Comment (ridiculousfish) [inline src/exec.cpp]: for new assertions we should add an "error message:"

     assert(j != nullptr && "Job should not be null");

File: src/signal.h [hunk 15]
```diff
@@ -40,4 +40,17 @@ bool signal_is_blocked();
...
+
+/// A RAII wrapper for signal_block/signal_unblock that triggers a signal block on creation, and then
+/// automatically releases the block when the object is destroyed, handling control flow and exceptions.
+struct signal_block_t {
+	signal_block_t() {
+		signal_block();
+	}
+
+	~signal_block_t() {
+		signal_unblock();
```
Comment (ridiculousfish) [inline src/signal.h]: Indentation looks off here; please use `./build_tools/style.fish` on every change.

File: src/enum_set.h [hunk 16]
```diff
@@ -0,0 +1,46 @@
+#pragma once
+
+#include <bitset>
+
+template<typename T>
+class EnumSet {
+private:
```
Comment (ridiculousfish) [inline src/enum_set.h]: I think a helpful typedef is warranted here:

    using base_type_t = std::underlying_type<T>::type;

to avoid repeating `std::underlying_type<T>::type`.

File: src/proc.cpp [hunk 17]
```diff
@@ -681,8 +684,9 @@ void proc_update_jiffies() {
 ///
 /// \param j the job to test
 ///
-/// \return 1 if buffers were available, zero otherwise
-static int select_try(job_t *j) {
+/// \return Tristate::yes() if buffers were ready, Tristate::no() if no buffers were ready,
+/// and Tristate::err() on error.
+static Tristate select_try(job_t *j) {
```
Comment (ridiculousfish) [inline src/proc.cpp]: Rather than this Tristate abstraction which IMO won't prove useful enough to justify, let's use an `enum class` here:

    enum class select_return_t {
          some_readable,   // some fd was readable
          none_readable,  // no fd was readable
          no_fds,  // no fds were present in the IO chain
    };

(probably you can think of better value names).

I think this will be more explicit.

**Comment by ridiculousfish** [comment]
Overall really nice work! My comments are mostly nits.

Did you want to get this into fish 3? My feeling is we should put it in the release after, this is a big change.

**Comment by mqudsi** [comment]
Thanks for reviewing, you basically poked at everything I was feeling "meh" about.

I would prefer not to include this in fish 3.0.

**Comment by faho** [comment]
>I would prefer not to include this in fish 3.0.

That would mean either putting off #5210 or finding some other, less invasive, way to fix it.

**Comment by mqudsi** [comment]
I guess it depends on how much testing this would see if it were included in fish 3.0, which depends on a) how many people are running off of `master` and b) when 3.0 will be frozen.

**Comment by zanchey** [comment]
I'd be happy to take it for the beta as that is likely to get more widespread testing.

File: src/proc.cpp [hunk 18]
```diff
@@ -363,96 +363,78 @@ typedef unsigned int process_generation_count_t;
...
+        if (pid > 0) {
+            // A child process has been reaped
+            handle_child_status(pid, status);
+            processed_count += 1;
+        }
+        else if (pid == 0) {
+            // No killed/dead children in this particular process group
+        } else {
+            // pid < 0 indicates an error. One likely failure is ECHILD (no children), which we
+            // break on, and is not considered an error. The other likely failure is EINTR,
```
[the remark this answers is not in the document]
Comment (mqudsi) [reply src/proc.cpp]: Bad comment, actual logic was correct.

**Comment by mqudsi** [comment]
@faho #3952 kept eating at me, 30dbdb0 should take care of it? I'm unsure how much of this is a hack and how much of it would ultimately be required anyway.

**Comment by mqudsi** [comment]
Now also closes #4238.

**Comment by faho** [comment]
I'm not quite sure what it is, but this feels really sluggish to use?

Typing is slower, the git prompt takes twice as long.

I've not been able to find a clean reproducer so far unfortunately.

**Comment by mqudsi** [comment]
@faho was it like that the list time you tried?

Thanks to all the rebasing, tracking it down to a particular change is going to be a PITA 😐

**Comment by faho** [comment]
>was it like that the list time you tried?

I don't _think_ so, but I've not specifically been on the lookout.

So far, it seems like there's multiple slowdowns here. Up to eb166b265 (the second commit), this behaves like master (~55ms). Then 4fa24b3fe slows down to ~85ms, and the full monty (550ecc5ec) goes down to ~190ms.

That's just running `fish_right_prompt` and `echo $cmd_duration` interactively.

Profiling it (via `fish --profile`) shows that e.g. `set -l changedFiles (command git diff --name-status 2>/dev/null | string match -r \\w)` slowed down from 4ms to 14ms. The command substitution is necessary.

So far the smallest reproducer I have found is:

```fish
set -l foo (command true | string match .)
```

This goes from 1ms to 11ms. Using `command true | true` is not enough.

**Comment by mqudsi** [comment]
It occurs to me that there's a chance `cmd_duration`'s calculation changed in the process. I would rely on an external tool (e.g. `bash -c 'time fish -c "foo"'` rather than fish's own metrics for this.

**Comment by faho** [comment]
>The first commit you mentioned 4fa24b3 was almost entirely aesthetic with the exception of using a bitset to store the job flags.

That's from eb166b2 to 4fa24b3, so including the preceding commits, including e.g. 05bcd0195. I didn't test every commit, only these (random-ish) points.

If you want, I can check more, but I felt like a nice reproducer was more important.

>It occurs to me that there's a chance cmd_duration's calculation changed in the process.

It's also noticeable, especially since my prompt is also affected, so I get quite a noticeable effect from prompt to prompt.

**Comment by mqudsi** [comment]
> If you want, I can check more, but I felt like a nice reproducer was more important.

Ah, thanks. That makes more sense. fwiw, I test via `git bisect` so that helps pin it down without having to try all the commits.

>It's also noticeable, especially since my prompt is also affected, so I get quite a noticeable effect from prompt to prompt.

I was just thinking aloud about other possible reasons why those commits had the problem, but your explanation makes that a moot point.

**Comment by mqudsi** [comment]
The entire design of `proc.cpp` makes it an impossible choice between working correctly or working fast. I pushed an update that tried to minimize the `waitpid` calls, but the architecture there is just wrong and the impact is still felt.

You don't timeout the `select(2)` calls every 10 milliseconds to check if processes have exited, then try to make that finish as quickly as possible so you can get back to processing IO. You just don't.

Waiting on processes to exit and waiting on IO to become available are two top-level operations that need to be run concurrently. Calling `waitpid(-1, ...)` enabled the use of `SIGCHLD` counting to determine if we call `waitpid` in the first place, but it was 100% wrong because posix wasn't architectured that way. Now we need to make several transitions between user code and system code because we can't wait on all processes in one go (there's no way to specify multiple pids or pgrps to wait on any of them).

The correct approach here would be either a separate thread with synchronization allowing the main thread to push the pgrps of constructed jobs to it, and this thread would be responsible for waiting on them to exit and setting their status correctly or a thread spawned per job (which is much cleaner) to wait on the job's children to exit and set their status accordingly. "Setting process status" is already (mostly) thread safe since at some point (long ago) it used to be done in a signal handler (probably on SIGCHLD directly). Or a separate thread to block until IO is ready and then handle the results.

Doing this doesn't just get rid of the slowdown from switching to `waitpid` by pgrp: it's even faster and less taxing than the old code since there's no constant timing out from the `select` call just to see if we need to handle the exiting of any processes.

I'm not sure what to do.

**Comment by ridiculousfish** [comment]
I agree with all this, though in fish's defense the "wait 10 msec" path is only in semi-weird cases involving redirections between external commands and fish functions; it's not the case for most executions.

The right thing to do here is whatever helps prepare us for to concurrent execution, which I think we can achieve in 3.1. Here's a sketch of how I expect it to work:

1. When a fish function (or certain builtins) is executed in a pipeline, a new exec thread is created for the function. This exec thread is conceptually analogous to a forked child. The function performs synchronous I/O (`read()`, `write()`) on this thread.

2. The parent thread's job is to wait for its "processes" some of which may be fish exec threads, and some of which are external. 

In this model, the parent thread no longer has to perform I/O. `select_try()` will just go away. `job_continue()` will do the following:

1. While I have a foreground (non-background) external command, `waitpid()` it.
2. Otherwise, wait for child exec threads (lots of possible mechanisms here).
3. Opportunistically reap background jobs.

Note that multiple threads will be running `job_continue()` at once, each waiting for their own children.

This PR moves us closer to this model since we no longer wait on all processes. So let's not tackle the `select_try()` issue yet since we're going to solve that via a big architectural shift.

**Comment by mqudsi** [comment]
So to be clear, your suggestion is that this PR is fine (any other issues notwithstanding) for now?

**Comment by faho** [comment]
>The right thing to do here is whatever helps prepare us for to concurrent execution, which I think we can achieve in 3.1.

The question I have is what we should do for 3.**0**?

We shouldn't release with #5210, but the perf here is bad enough that I would not want to release with this solution (which is a really nice piece of work, and seems to solve most problems with job control! Great job @mqudsi!).

Would it be possible to merge just part of this? Specifically up to eb166b265fb181ce979de01b0e552fb0665603e4, since 514eea9358f3d8b15cbd4d5fb25fd47edcc3619e is the really juicy part, and that has basically 0 performance impact.

Any further than that and it gets quite bad and noticeable. Note that we're not talking about a couple of percent here, this is 30% on the git prompt, and probably most completions.

**Comment by mqudsi** [comment]
Yeah, I guess I wasn't clear. I know what should be done, just not sure what should be done now. I guess now that I have a blessing to introduce threads into fish core I can try to hack something in temporarily, but I'm not sure if there's a place where that's possible without ending up with the rewrite.

**Comment by mqudsi** [comment]
@faho would you be so kind as to test it again? I found a (fragile and convoluted) approach that lets us use the SIGCHLD count to elide waitpid calls under certain cases.

**Comment by faho** [comment]
>My expect test script is running ~20% faster under keep_zombies than under master.

I can confirm that! Very nice!

**Comment by faho** [comment]
However, this is missing a `#include <functional>` in common.h for me (gcc 8.2.1). You might want to add that!

File: src/proc.cpp [hunk 19]
```diff
@@ -395,35 +428,60 @@ static bool process_mark_finished_children(bool block_on_fg) {
...
-            // at a time. We do bypass future waits in case of error, however.
-            if (errno != ECHILD) {
-                has_error = true;
-                wperror(L"waitpid in process_mark_finished_children");
+        // waitpid(2) returns 1 process each time, we need to keep calling it until we've reaped all
+        // children of the pgrp in question or else we can't reset the dirty_state flag. In all
+        // cases, calling waitpid(2) is faster than potentially calling select_try() on a process
+        // that has exited, which will force us to wait the full timeout before coming back here and
+        // calling waitpid() again.
+        while (true) {
```
Comment (faho) [inline src/proc.cpp]: Isn't this a bit clearer as `while (auto pid = waitpid`?

Comment (faho) [reply src/proc.cpp]: (I'm not a massive fan of `while (true)` because that means you need to manually account for all possibilities to not have an infinite loop)

File: src/proc.cpp [hunk 20]
```diff
@@ -395,35 +428,60 @@ static bool process_mark_finished_children(bool block_on_fg) {
...
+                if (errno != ECHILD) {
+                    has_error = true;
+                    wperror(L"waitpid in process_mark_finished_children");
+                }
+                break;
             }
         }
     }
 
+    // Yes, the below can be collapsed to a single line, but it's worth being explicit about it with
```
Comment (faho) [inline src/proc.cpp]: I _would_ actually shorten this to:

```c++
// If we skipped any jobs, we can't definitely say whether all children were reaped.
// If we didn't, we can just return next time if we got no SIGCHLD (i.e. fresh children to reap).
dirty_state = jobs_skipped;
```

File: src/proc.cpp [hunk 21]
```diff
@@ -362,27 +362,60 @@ static bool process_mark_finished_children(bool block_on_fg) {
...
+    // child process in that job if we use SIGCHLD count as the only metric for whether or not
+    // waitpid() is called.
+    // Without this optimization, the slowdown caused by calling waitpid() even just once each time
+    // `process_mark_finished_children()` is called is rather obvious (see the performance-related
+    // discussion in #5219), making it worth the complexity of this heuristic.
+
+    /// Tracks whether or not we received SIGCHLD without checking all jobs (due to jobs under
+    /// construction), forcing a full waitpid loop.
+    static bool dirty_state = true;
+    static size_t last_jobs_hash = -1;
```
Comment (faho) [inline src/proc.cpp]: Is this used anywhere?

File: src/proc.h [hunk 22]
```diff
@@ -316,6 +319,9 @@ class job_iterator_t {
         return job;
     }
 
+    /// Returns a hash of all jobs currently running that can be used to determine if jobs have
+    /// changed. Does not reflect changes to the states of these jobs.
+    size_t hash() const;
```
Comment (faho) [inline src/proc.h]: Where is this used?

File: src/postfork.cpp [hunk 23]
```diff
@@ -63,39 +63,56 @@ static void debug_safe_int(int level, const char *format, int val) {
...
-            narrow_string_safe(command, j->command_wcstr());
-
-            debug_safe(
-                1, "Could not send own process %s, '%s' in job %s, '%s' from group %s to group %s",
-                pid_buff, argv0, job_id_buff, command, getpgid_buff, job_pgid_buff);
-
-            safe_perror("setpgid");
-            retval = false;
+
+        while (int result = setpgid(p->pid, j->pgid) != 0) {
```
Comment (faho) [inline src/postfork.cpp]: This groups like

```
(int result = setpgid()) != 0
```

and not like

```
int result = (setpgid() != 0)
```

right?

(I can never recall operator precedence so I just add parens everywhere)

File: src/postfork.cpp [hunk 24]
```diff
@@ -63,39 +63,56 @@ static void debug_safe_int(int level, const char *format, int val) {
...
+            if (result == EPERM) {
+                // The setpgid(2) man page says that EPERM is returned only if attempts are made to
+                // move processes into groups across session boundaries (which can never be the case
+                // in fish, anywhere) or to change the process group ID of a session leader (again,
+                // can never be the case). I'm pretty sure this is a WSL bug, as we see the same
+                // with tcsetpgrp(2) in other places and it disappears on retry.
+                debug_safe(2, "setpgid(2) returned EPERM. Retrying");
+            }
+            else if (result == EINTR) {
```
Comment (faho) [inline src/postfork.cpp]: Don't we usually let the "else" ride on the closing bracket?

```c++
} else if
```

?

File: src/exec.cpp [hunk 25]
```diff
@@ -996,6 +998,32 @@ void exec_job(parser_t &parser, job_t *j) {
...
+    // job id (and therefore pgrp) each time, but always from the main thread. This breaks terminal
+    // control since new pgrps take terminal control away from commands upstream in a different pgrp.
+    // We try to work around this with a heuristic to determine whether to reuse the same pgrp as the
+    // last-spawned pgrp if part of an existing job pipeline (keeping in mind that new jobs are
+    // recursively started for both foreground and background jobs, and that a function can expand
+    // to more than one external command, one (or more?) of which may want to read from upstream or
+    // write to downstream of a pipe.
+    // By keeping track of (select) "jobs in flight" we can try to marshall newly-created external
+    // processes into existing pgrps.
+    static std::stack<job_t *> active_jobs{};
```
Comment (faho) [inline src/exec.cpp]: This entire thing strikes me as a bit of a hack, to be honest.

(The "real" solution is probably to pass the job along in exec_job, but that then means passing it all through the parser and that's just annoying)

I _think_ it works (and it seems to in actual tests), though.

Is there any way that a job in active_jobs becomes stale?

File: src/exec.cpp [hunk 26]
```diff
@@ -1031,43 +1031,6 @@ void exec_job(parser_t &parser, job_t *j) {
         }
     }
 
-    // When running under WSL, create a keepalive process unconditionally if our first
```
Comment (faho) [inline src/exec.cpp]: There is absolutely no way somebody is running "old WSL"?

File: src/proc.cpp [hunk 27]
```diff
@@ -515,6 +515,8 @@ static int process_clean_after_marking(bool allow_interactive) {
 
             // TODO: The generic process-exit event is useless and unused.
             // Remove this in future.
+            // Update: This event is used for cleaning up the psub temporary files and folders.
```
Comment (faho) [inline src/proc.cpp]: Huh? Is this the same event as the "--on-job-exit caller" event?

File: src/proc.cpp [hunk 28]
```diff
@@ -702,20 +703,20 @@ static int select_try(job_t *j) {
...
 
     if (maxfd >= 0) {
-        int retval;
-        struct timeval tv;
+        struct timeval timeout;
 
-        tv.tv_sec = 0;
-        tv.tv_usec = 10000;
+        timeout.tv_sec = 0;
+        timeout.tv_usec = 10000;
```
Comment (faho) [inline src/proc.cpp]: Btw: Why is this 10ms? Even millliseconds is really quite long in computer time, so wouldn't e.g. 1ms suffice?

File: src/proc.cpp [hunk 29]
```diff
@@ -794,12 +791,16 @@ bool terminal_give_to_job(const job_t *j, bool cont) {
         // 4.4.0), EPERM does indeed disappear on retry. The important thing is that we can
         // guarantee the process isn't going to exit while we wait (which would cause us to possibly
         // block indefinitely).
-        while (tcsetpgrp(STDIN_FILENO, j->pgid) != 0) {
-            debug(3, "tcsetpgrp failed");
+        while (true) {
```
Comment (faho) [inline src/proc.cpp]: I actually prefer the old loop condition.

File: src/proc.cpp [hunk 30]
```diff
@@ -754,19 +753,17 @@ static void read_try(job_t *j) {
...
+bool terminal_give_to_job(const job_t *j, bool restore_attrs) {
     if (j->pgid == 0) {
         debug(2, "terminal_give_to_job() returning early due to no process group");
         return true;
     }
 
-    signal_block();
+    // RAII wrappers must have a name so that their scope is tied to the function as it is legal for
+    // the compiler to construct and then immediately deconstruct unnamed objects otherwise.
+    signal_block_t signal_block;
```
Comment (faho) [inline src/proc.cpp]: This stuff is nice!

But let me just say that I think whoever named a bunch of C++ idioms has no naming skills whatsoever. RAII is, as a term, crap.

File: src/proc.h [hunk 31]
```diff
@@ -11,7 +11,7 @@
 #include <termios.h>
 #include <unistd.h>
 
-#include <list>
+#include <deque>
```
Comment (faho) [inline src/proc.h]: Have you tried vector? Any benchmarks?

From all the benchmarks I've seen, list is pretty much useless for almost all workloads (cache misses were the main issue IIRC), but vector is often nice.

See e.g. https://baptiste-wicht.com/posts/2012/12/cpp-benchmark-vector-list-deque.html and https://www.youtube.com/watch?v=YQs6IC-vgmo.

Also if both performed the same we should prefer vector because we're already using it.

File: src/proc.cpp [hunk 32]
```diff
@@ -363,96 +363,80 @@ typedef unsigned int process_generation_count_t;
 /// the SIGCHLD signal handler, and therefore does not need atomics or locks.
 static volatile process_generation_count_t s_sigchld_generation_cnt = 0;
```
Comment (faho) [inline src/proc.cpp]: If we're not using it anymore, why is it still there?

File: src/proc.cpp (hunk 28 above)
Comment (faho) [reply src/proc.cpp]: This used to be 10 _seconds_ from the initial revision up to 6b8e7b16f6d4e11e168e3ce2effe2d8f0a53b184.

https://sourceforge.net/p/fish/mailman/message/23293756/ is the mail that included the patch, and the justification for 10ms seems to be "shorter than 5s, still long enough that it's not busy-waiting". But 10ms still seems to be _really_ long.

File: src/proc.cpp (hunk 32 above)
Comment (mqudsi) [reply src/proc.cpp]: We're using it now.

File: src/proc.h (hunk 22 above)
Comment (mqudsi) [reply src/proc.h]: No, sorry that entire commit should be dropped. I used to use a snapshot of the jobs to determine if we can safely elide waitpid(2) calls, but that logic has been changed now.

File: src/postfork.cpp (hunk 23 above)
Comment (mqudsi) [reply src/postfork.cpp]: Good catch.

File: src/exec.cpp (hunk 25 above)
Comment (mqudsi) [reply src/exec.cpp]: It absolutely is a hack. But the entire parser approach is to set up a new context for the evaluation of functions and I broke too many things when I tried to change that.

`active_jobs` only contains `job_t` instances that haven't yet left `exec_job`, to keep track of the parent in event of recursive `exec_job` calls due to evaluation of functions and blocks. Jobs are removed from `active_jobs` before `exec_job` ends, so they're guaranteed to always be still "in execution" and very much valid.

I *can* change `exec_job` to take a `shared_ptr<job_t>` since that's what we actually originally have then decompose it to to a raw pointer for some reason, but there's really no need, it's guaranteed safe.

File: src/proc.cpp (hunk 27 above)
Comment (mqudsi) [reply src/proc.cpp]: I know, I was confused too. `PROCESS_EXIT` is fired from two places in the codebase and I can't see where it's used. This PR is already getting out of hand so I don't want to figure out why it breaks the job-exit event/the psub cleanup, but it does.

File: src/proc.h (hunk 31 above)
Comment (mqudsi) [reply src/proc.h]: `deque` is like a `vector` but with more efficient insert at the head too, not just the end. All our inserts were to the top of the list, so we should have actually changed this to a vector *plus* changed our view of the jobs list from top-to-bottom to bottom-to-top (just using `rbegin()` and `rend()` in iteration would have sufficed), but we can do that some other time.

File: src/postfork.cpp (hunk 24 above)
Comment (mqudsi) [reply src/postfork.cpp]: I know we do with final `} else {` clauses, but I wasn't sure about `} else if (...) {` but a quick check with `ag '\}\n\s*else if' -c` reveals you are correct.

File: src/proc.cpp (hunk 32 above)
Comment (faho) [reply src/proc.cpp]: Ah, sorry, I was going commit-for-commit, and the message for a5a23c57d82faa60a00dd6f7cd618a80c92c7c7d ("Overhaul behavior of `process_mark_finished_children()`") says:

>We're not using the SIGCHLD count in s_sigchld_generation_cnt for
anything any more, as it's not actually a reliable metric

File: src/proc.h (hunk 31 above)
Comment (faho) [reply src/proc.h]: Yeah, fair enough!

File: src/proc.cpp (hunk 27 above)
Comment (faho) [reply src/proc.cpp]: Oh, yeah, sure, by all means keep this as-is!

File: src/exec.cpp (hunk 25 above)
Comment (mqudsi) [reply src/exec.cpp]: I added a HACK warning and explanation of the preferred route plus complications you'll encounter going that way.

File: src/proc.cpp (hunk 28 above)
Comment (mqudsi) [reply src/proc.cpp]: Good job digging that up. 10ms is long, but 1ms timeouts have a noticeable CPU cost. I would rather just leave this at 10ms for now until we do the concurrency changes we were discussing, at which point the timeout can become `-1` and fish can properly react to both IO and child process exits without polling.

File: src/proc.cpp (hunk 29 above)
Comment (mqudsi) [reply src/proc.cpp]: I agree. I think during refactoring and rebasing a billion times over the final code works by simply plugging `tcsetpgrp` back into the condition but at some point in the middle that wasn't possible. Reverted.

File: src/proc.cpp (hunk 30 above)
Comment (mqudsi) [reply src/proc.cpp]: 😄 what would you do if I threw in a SFINAE or two in there?

File: src/exec.cpp (hunk 26 above)
Comment (mqudsi) [reply src/exec.cpp]: Of course there is. But are we going to burden our codebase forever with junk working around bugs while WSL reaches maturity? It's a tradeoff between when fish 3.0 gets and released and adoption of the latest WSL releases as time goes on, and it's easy enough to tell users running into pgrp-related errors (`tcsetpgrp`/`setpgid`, primarily) under WSL to update their Windows.

Keep in mind that WSL isn't on by default under Windows 10 and it's only the most tech savvy Windows users that will know what WSL is and use it.

File: src/proc.cpp (hunk 32 above)
Comment (mqudsi) [reply src/proc.cpp]: Understood. I actually debated deleting it in that same commit but left it around to see if we would need it later (which proved to be the case). I don't think I want to merge a5a23c5 with the waitpid optimizations commit, I would rather they be two separate, testable/bisectable chunks.

File: src/postfork.cpp (hunk 23 above)
Comment (mqudsi) [reply src/postfork.cpp]: This was actually even more broken than that, I was testing the 0/1 `result` instead of `errno` 🤦‍♂️

File: src/proc.cpp (hunk 21 above)
Comment (mqudsi) [reply src/proc.cpp]: Nope. As mentioned, that entire commit was part of a different optimization strategy and has now been dropped via rebase.

File: src/proc.cpp (hunk 20 above)
Comment (mqudsi) [reply src/proc.cpp]: Very well then! :)

File: src/proc.cpp (hunk 19 above)
Comment (mqudsi) [reply src/proc.cpp]: Changed. 

rust's preference for the unconditional `loop` over `while ...` has gotten to me, and I found it more logical to explicitly "handle" all possible results of the `waitpid` call instead of split the handling across the while condition and inside the body.

File: src/exec.cpp (hunk 26 above)
Comment (faho) [reply src/exec.cpp]: I actually did not know that! I thought it was an actual thing now, with releases and such!

File: src/proc.cpp (hunk 19 above)
Comment (faho) [reply src/proc.cpp]: AFAIK rust has compiler support for checking that you handled all possible results. This is C++, which... doesn't.

**Comment by mqudsi** [comment]
Thanks for testing and reviewing, @faho. I appreciate the confirmation about the performance concerns being put to rest (thank God!) and the other feedback.

> However, this is missing a #include <functional> in common.h for me (gcc 8.2.1). You might want to add that!

It's odd that [travis didn't catch that](https://travis-ci.org/fish-shell/fish-shell/builds/440904110?utm_source=github_status&utm_medium=notification), but I've fixed it in the latest rebase, along with the other issues you pointed out.

File: src/proc.cpp (hunk 32 above)
Comment (faho) [reply src/proc.cpp]: Okay.

File: src/proc.cpp (hunk 19 above)
Comment (mqudsi) [reply src/proc.cpp]: Very fair point!

**Comment by faho** [comment]
>It's odd that travis didn't catch that

Travis is basically always on the edge of Ubuntu EOL. Don't expect new compiler versions there!

**Comment by faho** [comment]
@mqudsi: There's a weird error message in the tests that I don't believe was there before - https://travis-ci.org/fish-shell/fish-shell/jobs/443932043#L1131:

>killpg: Invalid argument

If I'm reading this correctly, this happens in tests/interactive.fish before the "Testing interactive functionality" message is printed.

**Comment by faho** [comment]
Yup, `source`ing test_util.fish STOPs in a weird state (PID = 0?), after

```fish
    exec ../test/root/bin/fish $script $args_for_test_script
```

It seems running `exec` in a script will do that.

**Comment by mqudsi** [comment]
Interesting. It only happens with a literal `source`.

`foo.fish` contains the following: `exec build/fish -c "echo hello"`

`fish foo.fish` runs  fine. But `fish -c 'source foo.fish` prints "killpg: invalid argument".

(There's no actual difference between those two commands, is there?)

**Comment by faho** [comment]
Okay, I got a nice reproducible crash here:

```fish
echo a >somefile
grep a somefile | grep c | grep d
```
results in:

```
<W> fish: Could not send job 2 ('command grep --color=auto $argv') with pgid 14699 to foreground
tcsetpgrp: Kein passender Prozess gefunden
<W> fish: Could not send job 2 ('command grep --color=auto $argv') with pgid 14699 to foreground
tcsetpgrp: Kein passender Prozess gefunden
<E> fish: /tmp/makepkg/fish-shell-git/src/fish-shell/src/proc.cpp:411: failed assertion: job_fg == nullptr && "More than one active, fully-constructed foreground job!"
<E> fish: Backtrace:
<E> fish: 0   job_reap(bool) + 0
<E> fish: 1   job_t::continue_job(bool) + 1032
<E> fish: 2   exec_job(parser_t&, job_t*) + 7028
<E> fish: 3   parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 3156
<E> fish: 4   parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 5   parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) + 193
<E> fish: 6   parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) + 1380
<E> fish: 7   int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) + 392
<E> fish: 8   parser_t::eval(std::shared_ptr<parsed_source_t const>, io_chain_t const&, block_type_t) + 146
<E> fish: 9   parser_t::eval(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, io_chain_t const&, block_type_t) + 224
<E> fish: 10  /usr/bin/fish(+0xaae43) [0x560f269c0e43]
<E> fish: 11  /usr/bin/fish(+0xaf557) [0x560f269c5557]
<E> fish: 12  /usr/bin/fish(+0xafee8) [0x560f269c5ee8]
<E> fish: 13  expand_string(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::vector<completion_t, std::allocator<completion_t> >*, int, std::vector<parse_error_t, std::allocator<parse_error_t> >*) + 647
<E> fish: 14  parse_execution_context_t::expand_arguments_from_nodes(std::vector<tnode_t<grammar::argument>, std::allocator<tnode_t<grammar::argument> > > const&, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >*, parse_execution_context_t::globspec_t) + 450
<E> fish: 15  parse_execution_context_t::populate_plain_process(job_t*, process_t*, tnode_t<grammar::plain_statement>) + 1011
<E> fish: 16  parse_execution_context_t::populate_job_process(job_t*, process_t*, tnode_t<grammar::statement>) + 231
<E> fish: 17  parse_execution_context_t::populate_job_from_job_node(job_t*, tnode_t<grammar::job>, block_t const*) + 322
<E> fish: 18  parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 1053
<E> fish: 19  parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 20  parse_execution_context_t::run_if_statement(tnode_t<grammar::if_statement>, block_t const*) + 315
<E> fish: 21  parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 2739
<E> fish: 22  parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 23  parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) + 193
<E> fish: 24  parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) + 1380
<E> fish: 25  int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) + 392
<E> fish: 26  void internal_exec_helper<grammar::job_list>(parser_t&, std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&) + 194
<E> fish: 27  exec_job(parser_t&, job_t*) + 8134
<E> fish: 28  parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 1870
<E> fish: 29  parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 30  parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) + 193
<E> fish: 31  parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) + 1380
<E> fish: 32  int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) + 392
<E> fish: 33  parser_t::eval(std::shared_ptr<parsed_source_t const>, io_chain_t const&, block_type_t) + 146
<E> fish: 34  parser_t::eval(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, io_chain_t const&, block_type_t) + 224
<E> fish: 35  /usr/bin/fish(+0xaae43) [0x560f269c0e43]
<E> fish: 36  /usr/bin/fish(+0xaf557) [0x560f269c5557]
<E> fish: 37  /usr/bin/fish(+0xafee8) [0x560f269c5ee8]
<E> fish: 38  expand_string(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::vector<completion_t, std::allocator<completion_t> >*, int, std::vector<parse_error_t, std::allocator<parse_error_t> >*) + 647
<E> fish: 39  parse_execution_context_t::expand_arguments_from_nodes(std::vector<tnode_t<grammar::argument>, std::allocator<tnode_t<grammar::argument> > > const&, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >*, parse_execution_context_t::globspec_t) + 450
<E> fish: 40  parse_execution_context_t::populate_plain_process(job_t*, process_t*, tnode_t<grammar::plain_statement>) + 1011
<E> fish: 41  parse_execution_context_t::populate_job_process(job_t*, process_t*, tnode_t<grammar::statement>) + 231
<E> fish: 42  parse_execution_context_t::populate_job_from_job_node(job_t*, tnode_t<grammar::job>, block_t const*) + 322
<E> fish: 43  parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 1053
<E> fish: 44  parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 45  parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) + 193
<E> fish: 46  parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) + 1380
<E> fish: 47  int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) + 392
<E> fish: 48  void internal_exec_helper<grammar::job_list>(parser_t&, std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&) + 194
<E> fish: 49  exec_job(parser_t&, job_t*) + 8134
<E> fish: 50  parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) + 1870
<E> fish: 51  parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) + 196
<E> fish: 52  parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) + 193
<E> fish: 53  parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) + 1380
<E> fish: 54  int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) + 392
<E> fish: 55  parser_t::eval(std::shared_ptr<parsed_source_t const>, io_chain_t const&, block_type_t) + 146
<E> fish: 56  parser_t::eval(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, io_chain_t const&, block_type_t) + 224
<E> fish: 57  /usr/bin/fish(+0xaae43) [0x560f269c0e43]
<E> fish: 58  /usr/bin/fish(+0xf7f73) [0x560f26a0df73]
<E> fish: 59  reader_readline(int) + 171
<E> fish: 60  reader_read(int, io_chain_t const&) + 525
<E> fish: 61  main + 4064
<E> fish: 62  __libc_start_main + 243
<E> fish: 63  _start + 46
```

**Comment by mqudsi** [comment]
I'm presuming grep is a function?

Are you on the latest version of the code? I fixed that a few days ago, it was caused by sharing pgrps across function jobs.

**Comment by faho** [comment]
>I'm presuming grep is a function?

Yup, the standard `--color=auto` thing.

>Are you on the latest version of the code?

It turns out I wasn't. I checked github, but that says you added commits "22 days ago" and "3 days ago" respectively. It does not like this rebasing business.

Could you therefore post a quick comment that you added something when you do?

>I fixed that a few days ago, it was caused by sharing pgrps across function jobs.

I can confirm the fix. (for the `grep` crash, that is. The `source`/killpg business still happens)

**Comment by mqudsi** [comment]
Yeah, GitHub loses it when rebasing. I just pushed a commit that fixed a regression that wasn't there the last time you tried it (fish high cpu when another program has control of the terminal). I previously also committed a fix for a hang when piping an external command to a function when the external command produces more output than can fit within the OS pipe buffer and that entire chain is in the foreground and buffering was at play, previously we would block on the foreground process with reading from the pipe causing the prior command to block waiting for the pipe to unblock.

I just pushed again with a fix with the killpg warning. It was a bug introduced in 1b1bc28c0ae0fd10e9d3854b1d8cc8125623e1d9 but didn't surface until the changes to job control, fish would detect that the script calling `exec`  hadn't terminated and try killing it too.

**Comment by mqudsi** [comment]
Sorry, there was a typo in the killpg fix. Fixed now.

**Comment by faho** [comment]
So, @mqudsi, @ridiculousfish, @zanchey: Can we merge this now?

I'd love to, since then we might get some testing in. It's also one of the few things left in the [3.0 milestone](https://github.com/fish-shell/fish-shell/milestone/18).

**Comment by mqudsi** [comment]
I guess the point of a pull request is for code review and for testing we're going to have to merge this into master sooner or later (thanks @comfortablynick for trying it out). 

I don't like making tentative changes to master that might need to be reverted, but I guess the need for testing here wins out over aesthetic cleanliness of `master` history. I can rebase, give it a once-over, and merge it into `master` and if there are any problems that bubble up, we can address them or temporarily revert, I suppose.

Reminding myself: I should add test cases for some of the transient bugs I ran into developing this branch. The problem is that I'm still not 100% on how the expect tests work and what type of deviations from the explicitly scripted responses it accepts.

**Comment by mqudsi** [comment]
It's done! 😬

**Comment by JoshCheek** [comment]
❤️ Ty for this!
