### PR TITLE
Handle recursive calls to complete

### LINKED ISSUE #3474: complete -C fails when recursing?
fish: 2.3.1, Arch Linux, urxvt 9.22

Enter `complete -C"type p"`: only functions and builtins will get printed.
`type` has the following completion definition:

`complete -c type -a "(complete -C(commandline -ct))" -x`

Can you confirm the issue?

### PR DESCRIPTION
**Pull request by krobelus**
---

The first commit prints an error when the recursion limit is exceeded,
to make sure the user notices.

The second commit raises the limit to 2, to support cases like in #3474.
Not sure whether it is a good idea to do that but it seems to work.

----

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.md

### CODE REVIEW

File: src/builtin_complete.cpp [hunk 1]
```diff
@@ -336,7 +336,11 @@ int builtin_complete(parser_t &parser, io_streams_t &streams, wchar_t **argv) {
         parser.libdata().transient_commandlines.push_back(do_complete_param);
         cleanup_t remove_transient([&] { parser.libdata().transient_commandlines.pop_back(); });
 
-        if (parser.libdata().builtin_complete_recursion_level < 1) {
+        // Allow at most two recursive calls to complete (#3474).
+        if (parser.libdata().builtin_complete_recursion_level >= 2) {
```
Comment (faho) [inline src/builtin_complete.cpp]: Is there a particular reason to limit this to 2? I'd personally give it the same limit as wrapping (24, defined directly in complete.cpp::walk_wrap_chain_recursive).

(and even that is mostly there as a defence against infinite loops, and isn't the full story - see #5638)

Comment (krobelus) [reply src/builtin_complete.cpp]: Not really any reason for a limit of 2 I think.
I have changed it to a hardcoded 24 now.

File: src/builtin_complete.cpp [hunk 2]
```diff
@@ -336,7 +336,11 @@ int builtin_complete(parser_t &parser, io_streams_t &streams, wchar_t **argv) {
         parser.libdata().transient_commandlines.push_back(do_complete_param);
         cleanup_t remove_transient([&] { parser.libdata().transient_commandlines.pop_back(); });
 
-        if (parser.libdata().builtin_complete_recursion_level < 1) {
+        // Allow a limited number of recursive calls to complete (#3474).
+        if (parser.libdata().builtin_complete_recursion_level >= 24) {
+            streams.err.append_format(
+                L"%ls: maximum recursive depth reached - consider using complete --wraps\n", cmd);
```
Comment (krobelus) [inline src/builtin_complete.cpp]: I guess the `consider using complete --wraps` is obsolete now with the higher limit

File: src/builtin_complete.cpp (hunk 1 above)
Comment (krobelus) [reply src/builtin_complete.cpp]: The wrap chain handling should probably also print an error message when the limit is reached, to tell the user that there is probably a cycle.

Comment (faho) [reply src/builtin_complete.cpp]: Yeah, that's probably correct. Tho we don't want to spam the error.

**Comment by faho** [comment]
Yeah, merged, thanks!
