### PR TITLE
set_color updates for bright colors, fixes for low/no-color terminals

### LINKED ISSUE #3176: fish doesn't understand the color white
I would like the current directory in my fish prompt to be light gray, as it was in bash before I started using fish. I tried running `set -U fish_color_cwd white` (since white is the closest color to light gray that is listed in the [`set_color` documentation](https://fishshell.com/docs/current/commands.html#set_color)) and it didn't do anything. The text was green after, just like it was before.

I then tried `set -U fish_color_cwd red` to see what happened and the text turned red, like I expected. Then I tried `set -U fish_color_cwd white --bold` and it became bold, but green again. It seems like it understands all of the colors I tried, but not white.

I am using fish 2.3.0 on OS X 10.11.5 and the built-in Terminal. Here is a screenshot demonstrating what is happening:
white not working in fish shell

### PR DESCRIPTION
**Pull request by floam**
## Description

In #3176 I noticed that the reason the addition of bright colors was also causing issues with `TERM=xterm` (on modern terminals), was that fish would generate invalid ANSI:
We assumed that it we could use tparm to emit color escapes as long as the color was under 16 or `max_colors` from terminfo was 256:
                                                                                          
```                                                                                                                                    
if (idx < 16 || term256_support_is_native()) {                                                                                                                          
    // Use tparm to emit color escape
    writembs(tparm(todo, idx);      
```
                                                                                                                
But if a terminal has `max_colors` (terminfo) of, say, 8,  here is what will occur as it is asked for a number higher than that (except `tparm` did the same thing in output.cpp):

```fish
> env TERM=xterm tput setaf 7 | xxd
00000000: 1b5b 3337 6d                             .[37m 
> env TERM=xterm tput setaf 9 | xxd
00000000: 1b5b 3338 6d                             .[39m
```
The first escape is good, that second escape is not valid. Bright colors should start at `\e[90m`:
```fish
> env TERM=xterm-16color tput setaf 9 | xxd
00000000: 1b5b 3931 6d                             .[91m
```

This is what caused "white" not to work in #3176 in Terminal.app. (On real 8-color terminals the bigger issue was that `white` should cause color 7, not color 15, addressed below)

So we replace the `< 16 || term256_support_is_native()`, with the latter function just checking if `max_colors` is 256 or not, with a function that takes an `int` and checks terminfo for the. colors supported by the terminal (really, we care that `tparm` can be expected not to output garbage.)

```c++
/// Returns true if we think tparm can handle outputting a color index                                                                                                  
static bool term_supports_color_natively(unsigned int c) { return max_colors >= c; }                                                                                    
...                                                                                                                                                                         
if (term_supports_color_natively(idx) {
    // Use tparm to emit color escape.
    writembs(tparm(todo, idx));
```

If terminfo can't do it, the "forced" escapes no longer use the fancy format when handling colors under 16, as this is not going to be compatible with low color terminals. The code before used:

```c++
else {
    char buff[16] = "";
    snprintf(buff, sizeof buff, "\x1b[%d;5;%dm", is_fg ? 38 : 48, idx);
```
I added an intermediate format for colors 0-15:
```c++
else {                                                                                                                                                                  
     // We are attempting to bypass the term here. Generate the ANSI escape sequence ourself.                                                                            
     char buff[16] = "";                                                                                                                                                 
     if (idx < 16) {                                                                                                                                                     
         snprintf(buff, sizeof buff, "\x1b[%dm", ((idx > 7) ? 82 : 30) + idx + !is_fg * 10);                                                                             
     } else {                                                                                                                                                            
         snprintf(buff, sizeof buff, "\x1b[%d;5;%dm", is_fg ? 38 : 48, idx);                                                                                             
     }
```

The PR also fixes the definition of color white, fixes color values for all colors. The non-brights were defined with the bright values and brights had something invented by fish. e.g. `FF0000` for *red* (instead of `800000`) and `FF5555` for *brred* (instead of `FF0000`).

I got rid of the hack in config.fish. For #2951, one thing we should do is decide if we really want to send ANSI at terminals with `max_colors <= 8`, if no, solve it in C++?

Fixes #3176, #2951

## TODOs:
- [x] Changes to fish usage are reflected in user documenation/manpages.
- [ ] Tests have been added for regressions fixed

### CODE REVIEW

File: share/tools/web_config/js/colorutils.js [hunk 1]
```diff
@@ -393,19 +393,32 @@ function master_color_for_color(color_str) {
...
-	if (str == 'blue') return '0000FF'
-	if (str == 'magenta') return 'FF00FF'
-	if (str == 'purple') return 'FF00FF'
-	if (str == 'cyan') return '00FFFF'
-	if (str == 'white') return 'FFFFFF'
-	if (str == 'normal') return ''
-	return str
+    str = str.toLowerCase();
+    if (str == 'black') return '000000';
+    if (str == 'red') return '800000';
```
Comment (faho) [inline share/tools/web_config/js/colorutils.js]: Wouldn't it be nice here to be consistent with other programs, particularly terminals?

From [wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), it seems X will use F00 for red, but 008000 for green and 00F for blue, like we currently do. Xterm is a bit weirder.

**Comment by faho** [comment]
The documentation changes are a definite ACK, and I think I'm okay with white->grey. I'd prefer it if we still accepted "grey" as an alternative name - `set_color` erroring out isn't a great experience.

I'll have to test this a bit, particularly in a VT.

File: share/tools/web_config/js/colorutils.js (hunk 1 above)
Comment (floam) [inline share/tools/web_config/js/colorutils.js]: There are good arguments for matching another terminal or some tangible standard. However if we will ever do something like have "set_color red" apply a 24bit color code instead of one of these 16 colors, I think there are also good arguments for very carefully picking out a great set of preferred colors that work well on both dark and light terminals. 

In the case above though, I was just going by this table, except for the colors which I left in for the sake of compatibility at their prior values that do not actually exist as named colors in ANSI (brown, purple, grey).

http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

Comment (floam) [inline share/tools/web_config/js/colorutils.js]: Huh, those few colors in the bright column for X are surprising (in a good way.) They're actually quite near what I end up using in my terminal configurations.

**Comment by floam** [comment]
ACK?

**Comment by floam** [comment]
> prefer it if we still accepted "grey" as an alternative name - set_color erroring out isn't a great experience.

We do. What I decided to do was remove them from the documentation and color list but make sure `set_color` does what the scripts using those values intend.

**Comment by faho** [comment]
>ACK?

http://www.catb.org/jargon/html/A/ACK.html, meaning 4. You really need to grow your beard :smiley:.

Okay, in a VT this seems to "just work" - `set_color` maps the argument to the 8+8 normal/bright colors, and everytime it hits a bright one the VT just ignores it.

In a monochrome TERM=vt100, this hits #2951 in full force.

>We do. What I decided to do was remove them from the documentation and color list but make sure set_color does what the scripts using those values intend.

Sorry, I should have tried before. I'm not sure if we shouldn't stick a note in the docs - "For compatibility, 'grey' is accepted as a synonym for white". Not having it in the list is probably right, though.

File: src/output.cpp [hunk 2]
```diff
@@ -37,15 +37,20 @@ static int (*out)(char c) = writeb_internal;
 /// Whether term256 and term24bit are supported.
 static color_support_t color_support = 0;
 
+
+/// Set the function used for writing in move_cursor, writespace and set_color and all other output
```
Comment (faho) [inline src/output.cpp]: What's up with the three "/" here? I see they've been here before, but why?

**Comment by floam** [comment]
> In a monochrome TERM=vt100, this hits #2951 in full force.

In what way? The wrapper script is nuked from config.fish, so I know not the error quoted on that issue, what exactly is the terminal receiving for escapes and exhibiting?

File: src/output.cpp (hunk 2 above)
Comment (floam) [inline src/output.cpp]: These are headerdoc strings.

**Comment by floam** [comment]
What result does the monochrome terminal give for `tput colors`?

**Comment by faho** [comment]
>What result does the monochrome terminal give for `tput colors`?

"-1".

> In what way? The wrapper script is nuked from config.fish, so I know not the error quoted on that issue, what exactly is the terminal receiving for escapes and exhibiting?

It prints nothing, which is annoying in combination with the cartesian product - `echo (set_color red)rose` would not print anything. Maybe `set_color` should at least print a newline, or am I missing something?

(Also I've noticed that, when I give `set_color` an RGB value, $fish_term24bit (set via config.fish because I have $KONSOLE_PROFILE_NAME set) takes precedence and it'll print the RGB sequence)

**Comment by floam** [comment]
Hm, `set_color` probably shouldn't print a newline. But I think any character that would effectively be a NOP and not take a column or cause a linebreak on a vt100 should suffice.

**Comment by faho** [comment]
>Hm, set_color probably shouldn't print a newline. 

Why not?

>But I think any character that would effectively be a NOP and not take a column or cause a linebreak on a vt100 should suffice.

Which do you have in mind? I'm leaning towards a '\n' because that's the most-used character at the end of a programs output, so it seems to be the least likely to cause issues. Also it'd work (by being eliminated) in a command substitution, which is how `set_color` is used the most.

Compare:

```fish
echo (printf '\n')banana | od -t x1z
echo (printf '\r')banana | od -t x1z
```

And non-ASCII characters are right out here (haven't seen a vt100 with emoji support yet).

**Comment by floam** [comment]
Isn't that going to... add a spurious linebreak scripts were not expecting when there isn't the cartesian product thing happening?

**Comment by floam** [comment]
I was thinking something like an escape sequence that does nothing.

**Comment by faho** [comment]
>Isn't that going to... add a spurious linebreak scripts were not expecting when there isn't the cartesian product thing happening?

You're right. I was under the impression we'd reset the terminal mode between commands, but we only do that for the prompt (which is why running `set_color red` interactively has no effect).

>I was thinking something like an escape sequence that does nothing.

Maybe the "reset" sequence (`\e[0m`)? I mean in a command substitution that'd be captured, but that's okay since you were expecting something to be captured anyway (e.g. checking for string-equivalency on a variable that includes a color sequence is usually a dumb idea).

**Comment by floam** [comment]
I think that fixed it.

File: share/functions/__fish_config_interactive.fish [hunk 3]
```diff
@@ -299,26 +299,6 @@ function __fish_config_interactive -d "Initializations that should be performed
         set -g fish_pager_color_description yellow
         set -g fish_pager_color_progress cyan
```
Comment (ridiculousfish) [inline share/functions/__fish_config_interactive.fish]: Do I understand correctly that what this function used to do (per commit f71e877f18037f71c00f81e30c1173f51c42a58c ) is now handled by the builtin set_color? That seems good if so.

Comment (floam) [inline share/functions/__fish_config_interactive.fish]: Not exactly. It does not mask off certain colors specifically for `TERM=linux` (or `TERM=vt100`), but the goal is it will work on a VT by not throwing escapes at it that are problematic.

**Comment by floam** [comment]
OK, I *think* this should stop causing the empty output with `echo (set_color red)foo` - I hope there aren't side effects.

**Comment by floam** [comment]
> (Also I've noticed that, when I give set_color an RGB value, $fish_term24bit (set via config.fish because I have $KONSOLE_PROFILE_NAME set) takes precedence and it'll print the RGB sequence)

Is that OK? (Because that's only set when you're *actually* in Konsole?)

File: src/builtin_set_color.cpp [hunk 4]
```diff
@@ -179,7 +179,9 @@ int builtin_set_color(parser_t &parser, io_streams_t &streams, wchar_t **argv) {
             write_color(rgb_color_t::black(), true /* is_fg */);
             writembs(tparm(exit_attribute_mode));
         } else {
-            write_color(fg, true /* is_fg */);
+            if (!write_color(fg, true /* is_fg */)) {
```
Comment (faho) [inline src/builtin_set_color.cpp]: This appears non-obvious and in need of a comment:

"If we can't write any color, write a reset sequence so cartesian products don't nix something like `echo (set_color foo)bar`. This _should_ work in monochrome terminals."

**Comment by faho** [comment]
>>(Also I've noticed that, when I give set_color an RGB value, $fish_term24bit (set via config.fish because I have $KONSOLE_PROFILE_NAME set) takes precedence and it'll print the RGB sequence)

>Is that OK? (Because that's only set when you're actually in Konsole?)

Yes, it should be okay. Just a bit surprising.

------

I've now retested this and it seems to work now with TERM=vt100 (just never setting any color) in what is actually Konsole.

**Comment by ridiculousfish** [comment]
These net changes look good. Can you please squash some commits and/or clean up the commit messages? In particular c2bd79809c0f5a4dd8cb73ecd3d23267eebb711e and 9bb2de926c0be6d8f406bb8a37982826f6901a55.

I haven't caught on up what the behavior change here is, I need to see what it's like.

**Comment by floam** [comment]
@ridiculousfish Let me know if that is any more straightforward. I simply squished most of the code changes together and redid the commit log to explain the behavior change.

**Comment by ridiculousfish** [comment]
Squashing looks good. I have some concerns about the commit messages:

8d48ba4e0cd6e7a9afe6f76b4c13186590fbc7db:
This is a great fix, but this makes me nervous: "I think this'll stop swallowing the cart. product". Well, does it or doesn't it? Also please elaborate on the issue in the commit message. We'll want to relnote it too.

817b19906128ab88bc0f2f237e20596577d81d27:
Please briefly mention the sort of update this is.

891896c79ca5a167af710cd3e18e925c074c8de9:
Wow! But this message is too long and detailed. For example it's not necessary to duplicate the code itself in the commit messages.

File: doc_src/set_color.txt [hunk 5]
```diff
@@ -2,36 +2,35 @@
 
 \subsection set_color-synopsis Synopsis
 \fish{synopsis}
-set_color [OPTIONS] [COLOR]
+`set_color` [OPTIONS] *VALUE*
```
Comment (ridiculousfish) [inline doc_src/set_color.txt]: These backticks and asterisks are showing up in the man page and the docs. Were you trying to get some particular styling here?

Comment (floam) [inline doc_src/set_color.txt]: Whoops. Yes. In the rest of the manpage backticks caused <tt> in HTML or boldness in `man`, and asterisks caused italics in HTML and underlines in the manpage.

These are all nice behaviors and match other manpages on my system for non-fish projects where command names are bolded and keywords are underlined.

**Comment by floam** [comment]
> Wow! This message is actually too long and detailed. For example it's not necessary to duplicate the code itself in the commit messages - we can find that through git.

This was mostly meant for you - so I've moved that to the top here and I'm doing a shorter one for the commit.

Thanks for the help!

**Comment by floam** [comment]
> This is a great fix, but this makes me nervous
I wasn't too confident when I committed it that there wouldn't be some kind of side effect of resetting all the time and didn't try it on a real monochrome terminal. But since you say it's a great fix, I feel better. 😃

**Comment by floam** [comment]
What we want to do for `max_colors = 8` "not really 8"  terminals like Linux is detect that and then enter bold mode and then write a color escape for idx = idx - 8; at a higher level before we are writing the escape, else we'll lose track of entering bold mode such that `was_bold` is correct . These actually have 8 more bright colors that people will see but it cannot be set independently of bold (which so we want to use the aixterm escapes whenever possible).

Once it's doing that the behavior here should be pretty nice.

**Comment by faho** [comment]
@floam: What's missing here? In my (not too thorough) tests I haven't noticed anything off.

**Comment by floam** [comment]
I'm just going to merge what's here and commit a further improvement in the works later. This needs more testing prior to the upcoming release and shouldn't be delayed further.

File: share/functions/__fish_config_interactive.fish [hunk 6]
```diff
@@ -24,14 +24,28 @@ function __fish_config_interactive -d "Initializations that should be performed
 
     #
     # If we are starting up for the first time, set various defaults
-    #
-    if not set -q __fish_init_1_50_0
+    #    
+    if not set -q __fish_init_2_39_8 # bump this to 2_40_0 when rolling release if anything changes after 9/10/2016
```
Comment (floam) [inline share/functions/__fish_config_interactive.fish]: I want folks to pound on it with 0-8 colors, bright colors, bold normal colors, and #RRBBGG colors. So I did this to blast away color settings. It doesn't need to be kept in for the real release.

**Comment by floam** [comment]
Ok, merging this. Hopefully we can shake out any bugs prior to release. The final TODO I'm hammering on to be committed later, brights for "8" color terminals.

> What we want to do for max_colors == 8 terminals like linux is if 8 < idx < 16, we enter bold mode at > a higher level than where most of the work was so far, such that was_bold is correct (else we'll lose > track of being in bold mode), and then do a color escape for idx - 8.

File: share/functions/__fish_config_interactive.fish [hunk 7]
```diff
@@ -22,42 +22,54 @@ function __fish_config_interactive -d "Initializations that should be performed
...
     # If we are starting up for the first time, set various defaults
-    #
-    if not set -q __fish_init_1_50_0
-        if not set -q fish_greeting
-            set -l line1 (printf (_ 'Welcome to fish, the friendly interactive shell') )
-            set -l line2 (printf (_ 'Type %shelp%s for instructions on how to use fish') (set_color green) (set_color normal))
-            set -U fish_greeting $line1\n$line2
+    #    
+    if not set -q __fish_init_2_39_8 # bump this to 2_4_0 when rolling release if anything changes after 9/10/2016
+        set -g colors_backup "$HOME/fish_previous_colors-(date).txt"
```
Comment (TimWolla) [inline share/functions/__fish_config_interactive.fish]: This does not properly insert the date. The file is literally named `fish_previous_colors-\(date\).txt`. I don't think this was indented, was it?

Comment (krader1961) [inline share/functions/__fish_config_interactive.fish]: Not only that but even if we supported command substitution inside quoted strings it is generally a bad idea to use the user locale for formatting the date in this type of context. It's almost always a better to use a fixed format such as ISO 8601. I'll take care of it.

Comment (floam) [inline share/functions/__fish_config_interactive.fish]: Why? it's just intended to be manually noticed by a developer with `ls` - not automatically restored or anything.

Comment (floam) [inline share/functions/__fish_config_interactive.fish]: Could also just put (random) in there . The file birth date will keep the needed information.

Comment (floam) [inline share/functions/__fish_config_interactive.fish]: Thanks for fixing it.

**Comment by floam** [comment]
>I do want to force any settings using deprecated color-names to reset on release, however. 

What we should probably just do is keep an init routine that will run on upgrade to 2.4.0, but what it does instead of "normalizing" colors (sorry, was a joke) by deleting them is replace previous names it encounters with the correct names.

grey -> white
brgrey -> brblack
brown -> yellow
white -> brwhite
purple -> magenta

**Comment by floam** [comment]
> That should prevent us from "teaching" deprecated color names through our defaults, and fix it so that colors display like how they did before this patch.

Actually, I should check: did we adjust the defaults after doing our boneheaded "white now refers to bright white" change which this PR reverted? If no, then we could just leave those as is and they'll return to the behavior as designed finally.
