### PR TITLE
Fix infinite prompt loop if status message is printed in prompt

### LINKED ISSUE #9796: Crashes in prompt cause a repaint loop
`fish_job_summary` calls `commandline -f repaint`, which, if it is called via something in fish_prompt, causes it to loop.

I found this when I noticed that fossil crashes if $PWD doesn't exist, so the test case is:

```fish
function fish_prompt; fossil branch current; end
mkdir foo
cd foo
rm -rf $PWD
```

It'll end up printing a constant stream of

> fish: Job 1, 'fossil branch current' terminated by signal SIGABRT (Abort)

until you press ctrl-c. While this should be a bug in fossil, the general principle stands.

I'm not sure how to detect this and turn fish_job_summary off.

### PR DESCRIPTION
**Pull request by ridiculousfish**
fish will print messages for some jobs when they exit abnormally, such as with SIGABRT. If a job exits abnormally inside the prompt, then (prior to this commit) fish would print the message and re-trigger the prompt, which could result in an infinite loop. This has existed for a very long time.

Fix it by reaping jobs after running the prompt, and NOT triggering a redraw based on that reaping. We still print the message but the prompt is not executed.

Add a test.

Fixes #9796

### CODE REVIEW

File: src/reader.rs [hunk 1]
```diff
@@ -4204,6 +4204,11 @@ impl<'a> Reader<'a> {
         // hack to work.
         reader_write_title(L!(""), zelf.parser, false);
 
+        // Reap jobs but do NOT trigger a repaint.
+        // This is to prevent infinite loops in case a job from the prompt triggers a repaint.
+        // See #9796.
+        job_reap(zelf.parser, true);
+
```
Comment (krobelus) [inline src/reader.rs:4211]: LGTM, this will fix it for foreground jobs in the prompt, which is the most common scenario (I can't think of a legit case for a background job that's not disowned).
