### PR TITLE
cd first, ask questions later

### LINKED ISSUE #7577: cd relies on stat(3), which on buggy filesystems may fail even if a directory exists
The linux system call `stat()` (stat(3) in linux man page) can return < 0 when invoked over a file or directory that reside in a not properly  configured filesystem (observed in misconfigured permission on fuse).
In that case `stat()` fail even if a directory exists, so `cd`ing to those directories fails and file/folder autocompletion (and probably every time fish use `stat()` in the filesystem) fails as well.
As reported and tested on gitter, `access()` apparently works, as does actually changing the directory.
The following [branch](https://github.com/faho/fish-shell/tree/cd-error2) solves the `cd` problem, but there is still work to do to get autocompletion to properly work.

### PR DESCRIPTION
**Pull request by faho**
Some filesystems are broken and error out on `stat(3)` of existing and
cd-able directories.

So we just try to `fchdir` and report errors later.

Fixes #7577.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

I have *absolutely no idea* how to test this - we need some way to have a `stat` fail but an `fchdir` succeed.

### CODE REVIEW

**Comment by zanchey** [comment]
> I have _absolutely no idea_ how to test this - we need some way to have a `stat` fail but an `fchdir` succeed.

https://github.com/trailofbits/ebpfault is probably the way to go, but requires root and a newish kernel. Sounds like a fun thing to play with though.

**Comment by zanchey** [comment]
See also https://www.scylladb.com/2016/02/16/fault-injection-filesystem-software-testing/

File: src/builtin_cd.cpp [hunk 1]
```diff
@@ -47,55 +47,69 @@ maybe_t<int> builtin_cd(parser_t &parser, io_streams_t &streams, wchar_t **argv)
...
-
-        status = wstat(dir, &buffer);
-        if (!status && S_ISDIR(buffer.st_mode)) {
-            streams.err.append_format(_(L"%ls: Permission denied: '%ls'\n"), cmd, dir_in.c_str());
-        } else {
-            streams.err.append_format(_(L"%ls: '%ls' is not a directory\n"), cmd, dir_in.c_str());
+    errno = 0;
+    auto best_errno = errno;
+
+    for (auto &dir: dirs) {
```
Comment (krobelus) [inline src/builtin_cd.cpp:63]: nit: this can probably be a `const auto &`

File: src/path.h [hunk 2]
```diff
@@ -64,6 +64,10 @@ wcstring_list_t path_get_paths(const wcstring &cmd, const environment_t &vars);
 maybe_t<wcstring> path_get_cdpath(const wcstring &dir, const wcstring &wd,
                                   const environment_t &vars);
```
Comment (krobelus) [inline src/path.h:65]: This declaration should then be removed.

Comment (krobelus) [reply src/path.h:65]: oops, nevermind

File: src/builtin_cd.cpp [hunk 3]
```diff
@@ -47,55 +47,69 @@ maybe_t<int> builtin_cd(parser_t &parser, io_streams_t &streams, wchar_t **argv)
...
+        wcstring norm_dir = normalize_path(dir);
+
+        // We need to keep around the fd for this directory, in the parser.
+        errno = 0;
+        autoclose_fd_t dir_fd(wopen_cloexec(norm_dir, O_RDONLY));
```
Comment (krobelus) [inline src/builtin_cd.cpp:68]: I think we prefer `{` for initialization, although I'm probably guilty of using `(` as well.

File: src/builtin_cd.cpp [hunk 4]
```diff
@@ -47,55 +47,69 @@ maybe_t<int> builtin_cd(parser_t &parser, io_streams_t &streams, wchar_t **argv)
...
+        bool success = dir_fd.valid() && fchdir(dir_fd.fd()) == 0;
+
+        if (!success) {
+            // If the directory doesn't exist, we ignore it and only error if none does.
+            // ENOENT is a low-priority error - if we found something with the name that isn't a directory, we error out.
```
Comment (krobelus) [inline src/builtin_cd.cpp:73]: This refers to the ENOTDIR case, right? The ENOENT case is described in the line above.
Also the second sentence is a bit confusing because we don't error out immediately but still try other CDPATH entries but I don't know how to word it differently.

**Comment by fabh2o** [comment]
I'm currently testing the branch, `cd` seems to works fine, `cd -` works too. Providing directly the name of the directory fails, tab completion fails too, but i know it's not the goal of this commit.
I have tried to get a reproducible non working example but with no chance.

**Comment by krobelus** [comment]
> For the saga of broken filesystem, if the current directory . or parent directory .. files are missing, running .. in fish gets The file '..' is not executable by this user but cd .. works fine.

`path_get_cdpath` is also used by `path_as_implicit_cd` which decides that a command like `..` is a directory (that we should cd to). This check is also used during highlighting. It would probably be quite ugly to make this highlighting or directory completion work - I imagine one could cd there and back instead of using stat.

Does file/directory completion work in bash? It seems they also stat each completion candidate by default in `append_to_match` in `lib/readline/complete.c:1857`. It seems difficult to do much besides merely listing all files/directories if stat doesn't work. Many other programs will fail as well. The only real solution is to fix the filesystem.

**Comment by krobelus** [comment]
> Providing directly the name of the directory fails

Do you mean that running something like `cd foo` fails when it shouldn't?

**Comment by fabh2o** [comment]
> Do you mean that running something like `cd foo` fails when it shouldn't?

No, i mean just run `foo`, as stated in [fish cd doc ](https://fishshell.com/docs/current/cmds/cd.html), where `foo` is the name of a directory in the current folder.


> Does file/directory completion work in bash?

Yes, both of them

**Comment by krobelus** [comment]
Ok, that's "implicit cd", the execution can be fixed by changing the call to `path_as_implicit_cd` in `src/parse_execution.cpp:864`.
Maybe we can reuse some of the new logic in builtin_cd.

I wonder how come completion works in bash. Do you have reproduction steps to configure the file system so we can test on that?

**Comment by fabh2o** [comment]
> Do you have reproduction steps to configure the file system so we can test on that?

None yet, i opened a [thread](https://forum.rclone.org/t/stat-3-fails-on-mounted-folder/21254/2) on the rclone forum (it mounts a remote filesystem via fuse) but had no help so far

**Comment by faho** [comment]
Note: I would be okay if we punted this to after 3.2 - I don't think it's important enough to block 3.2, given that it's a workaround for a broken filesystem that isn't used often, and that it's in a critical-ish path.

File: src/builtin_cd.cpp [hunk 5]
```diff
@@ -47,55 +47,69 @@ maybe_t<int> builtin_cd(parser_t &parser, io_streams_t &streams, wchar_t **argv)
...
+        streams.err.append_format(_(L"%ls: '%ls' is not a directory\n"), cmd, dir_in.c_str());
+    } else if (best_errno == ENOENT) {
+        streams.err.append_format(_(L"%ls: The directory '%ls' does not exist\n"), cmd,
+                                  dir_in.c_str());
+    } else if (best_errno == EROTTEN) {
+        streams.err.append_format(_(L"%ls: '%ls' is a rotten symlink\n"), cmd, dir_in.c_str());
+    } else if (best_errno == EACCES) {
+        streams.err.append_format(_(L"%ls: Permission denied: '%ls'\n"), cmd, dir_in.c_str());
+    } else {
+        wperror(L"cd");
```
Comment (ridiculousfish) [inline src/builtin_cd.cpp:105]: Probably should restore `errno` before calling wperror

**Comment by ridiculousfish** [comment]
Left one review comment; otherwise changes LGTM

**Comment by faho** [comment]
Moving this to 3.3. It should also be done for implicit cd, and it needs to be tested.
